version: '3.9'

services:

  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    volumes:
      - zookeeper:/bitnami/zookeeper

  kafka:
    container_name: kafka
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka:/bitnami/kafka
    depends_on:
      - zookeeper

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  clickhouse-keeper:
    container_name: clickhouse-keeper
    image: clickhouse/clickhouse-keeper:23.9
    volumes:
      - clickhouse_keeper:/var/lib/clickhouse
      - ./clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    ports:
      - 9181:9181

  clickhouse-01:
    container_name: clickhouse-01
    image: clickhouse/clickhouse-server:23.9
    ulimits:
      nofile: 262144
    volumes:
      - clickhouse_01:/var/lib/clickhouse
      - clickhouse_01_logs:/var/log/clickhouse-server
      - clickhouse_01_backup:/var/lib/clickhouse/backups
      - ./clickhouse/config-01.xml:/etc/clickhouse-server/config.d/config.xml
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ../schema.proto:/var/lib/clickhouse/format_schemas/schema.proto
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - 8123:8123
      - 9000:9000
    depends_on:
      - clickhouse-keeper

  clickhouse-02:
    container_name: clickhouse-02
    image: clickhouse/clickhouse-server:23.9
    ulimits:
      nofile: 262144
    volumes:
      - clickhouse_02:/var/lib/clickhouse
      - clickhouse_02_logs:/var/log/clickhouse-server
      - clickhouse_02_backup:/var/lib/clickhouse/backups
      - ./clickhouse/config-02.xml:/etc/clickhouse-server/config.d/config.xml
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ../schema.proto:/var/lib/clickhouse/format_schemas/schema.proto
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - 8124:8123
      - 9001:9000
    depends_on:
      - clickhouse-keeper

volumes:
    systemdb:
    zookeeper:
    kafka:
    clickhouse_01:
    clickhouse_01_logs:
    clickhouse_01_backup:
    clickhouse_02:
    clickhouse_02_logs:
    clickhouse_02_backup:
    clickhouse_keeper: